python ./01Knapsack.py dp_check_optimum_value.csv TopDownDynamicProgramming t low-dimensional/f1_l-d_kp_10_269 295 - - 
python ./01Knapsack.py dp_check_optimum_value.csv BottomUpDynamicProgramming t low-dimensional/f1_l-d_kp_10_269 295 - - 
python ./01Knapsack.py dp_check_optimum_value.csv TopDownDynamicProgramming t low-dimensional/f2_l-d_kp_20_878 1024 - - 
python ./01Knapsack.py dp_check_optimum_value.csv BottomUpDynamicProgramming t low-dimensional/f2_l-d_kp_20_878 1024 - - 
python ./01Knapsack.py dp_check_optimum_value.csv TopDownDynamicProgramming t low-dimensional/f3_l-d_kp_4_20 35 - - 
python ./01Knapsack.py dp_check_optimum_value.csv BottomUpDynamicProgramming t low-dimensional/f3_l-d_kp_4_20 35 - -
python ./01Knapsack.py dp_check_optimum_value.csv TopDownDynamicProgramming t low-dimensional/f4_l-d_kp_4_11 23 - - 
python ./01Knapsack.py dp_check_optimum_value.csv BottomUpDynamicProgramming t low-dimensional/f4_l-d_kp_4_11 23 - - 
python ./01Knapsack.py dp_check_optimum_value.csv TopDownDynamicProgramming t low-dimensional/f6_l-d_kp_10_60 52 - - 
python ./01Knapsack.py dp_check_optimum_value.csv BottomUpDynamicProgramming t low-dimensional/f6_l-d_kp_10_60 52 - - 
python ./01Knapsack.py dp_check_optimum_value.csv TopDownDynamicProgramming t low-dimensional/f7_l-d_kp_7_50 107 - - 
python ./01Knapsack.py dp_check_optimum_value.csv BottomUpDynamicProgramming t low-dimensional/f7_l-d_kp_7_50 107 - -
python ./01Knapsack.py dp_check_optimum_value.csv TopDownDynamicProgramming t low-dimensional/f8_l-d_kp_23_10000 9767 - - 
python ./01Knapsack.py dp_check_optimum_value.csv BottomUpDynamicProgramming t low-dimensional/f8_l-d_kp_23_10000 9767 - -
python ./01Knapsack.py dp_check_optimum_value.csv TopDownDynamicProgramming t low-dimensional/f9_l-d_kp_5_80 130 - - 
python ./01Knapsack.py dp_check_optimum_value.csv BottomUpDynamicProgramming t low-dimensional/f9_l-d_kp_5_80 130 - - 
python ./01Knapsack.py dp_check_optimum_value.csv TopDownDynamicProgramming t low-dimensional/f10_l-d_kp_20_879 1025 - - 
python ./01Knapsack.py dp_check_optimum_value.csv BottomUpDynamicProgramming t low-dimensional/f10_l-d_kp_20_879 1025 - - 
python ./01Knapsack.py dp_check_optimum_value.csv TopDownDynamicProgramming t large_scale/knapPI_1_200_1000_1 11238 - - 
python ./01Knapsack.py dp_check_optimum_value.csv BottomUpDynamicProgramming t large_scale/knapPI_1_200_1000_1 11238 - - 
python ./01Knapsack.py dp_check_optimum_value.csv TopDownDynamicProgramming t large_scale/knapPI_2_5000_1000_1 44356 - - 
python ./01Knapsack.py dp_check_optimum_value.csv BottomUpDynamicProgramming t large_scale/knapPI_2_5000_1000_1 44356 - - 
python ./01Knapsack.py dp_check_optimum_value.csv TopDownDynamicProgramming t large_scale/knapPI_3_5000_1000_1 72505 - - 
python ./01Knapsack.py dp_check_optimum_value.csv BottomUpDynamicProgramming t large_scale/knapPI_3_5000_1000_1 72505 - - 